# Generated by Django 5.1.7 on 2025-03-29 22:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_comment_comment_id_alter_likes_like_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='comment',
            name='flagged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='flagged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post_id', 'created_at'], name='comment_post_id_a28bde_idx'),
        ),
        migrations.AddIndex(
            model_name='likes',
            index=models.Index(fields=['post_id', 'user_id'], name='likes_post_id_46821f_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['user_id', 'created_at'], name='post_user_id_e74e29_idx'),
        ),
    ]
