# Generated by Django 5.1.7 on 2025-03-29 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='violationnotification',
            old_name='user_id',
            new_name='user',
        ),
    ]
