# Generated by Django 5.1.7 on 2025-03-29 23:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_creaeted_at_user_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserViolation',
            fields=[
                ('violation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('violation_count', models.PositiveIntegerField(default=0)),
                ('last_violation_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_violation',
            },
        ),
    ]
