# Generated by Django 5.1.7 on 2025-03-29 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userviolation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userviolation',
            old_name='user_id',
            new_name='user',
        ),
    ]
